runtime: python39
entrypoint: gunicorn -b :$PORT app:app

env_variables:
  FIREBASE_SERVICE_ACCOUNT: >
    {
      "type": "service_account",
      "project_id": "mystocktrading-334c9",
      "private_key_id": "131e11984e007b905ebbc465f687b856b88045b9",
      "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCauSmOI/feWlpk\n...<YOUR REMAINING KEY>\n-----END PRIVATE KEY-----\n",
      "client_email": "firebase-adminsdk-fbsvc@mystocktrading-334c9.iam.gserviceaccount.com",
      "client_id": "115293142522771426115",
      "auth_uri": "https://accounts.google.com/o/oauth2/auth",
      "token_uri": "https://oauth2.googleapis.com/token",
      "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
      "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40mystocktrading-334c9.iam.gserviceaccount.com",
      "universe_domain": "googleapis.com"
    }

handlers:
  - url: /.*
    script: auto
